version: 2
models:
  - name: stg_etudiant
    description: Modèle de staging contenant les données nettoyées des étudiants

    columns: 
      - name: user_id
        description: Identifiant pseudonymisé de l'étudiant. Peut apparaître plusieurs fois selon l'année ou la formation.
        data_tests:
          - not_null  # Vérifie que l'identifiant n'est jamais vide

      - name: gender
        description: Genre de l'étudiant
        tests:
          - accepted_values:
              arguments: 
                values: ['F','M','unknown'] # Vérifie que seules ces valeurs sont possibles

      - name: year_path_started
        description: Année de début du parcours de formation de l'étudiant
        tests:
          - accepted_values:
              arguments:
                values: [2022, 2023, 2024, 2025]  # Vérifie que seules les années présentes dans les données sources sont utilisées
